<?php 

return [
	'name' => 'Kalipso Next',
	'description' => '{"en":"test","tr":"test2"}',
	'contact_email' => 'halillusion@gmail.com',
	'separator' => '-',
	'language' => 'tr',
	'default_user_role' => 1,
	'ssl' => false,
	'log' => true,
	'maintenance_mode' => true,
	'maintenance_mode_desc' => '{"en":"naber","tr":"bebek"}',
	'mail_send_type' => 'server',
	'smtp_address' => 'smtp.yandex.com.tr',
	'smtp_port' => 587,
	'smtp_email_address' => 'hi@example.com',
	'smtp_email_pass' => 'password',
	'smtp_secure' => 'tls',
	'mail_queue' => true,
	'view_cache' => true,
	'db_cache' => true,
	'route_cache' => true,
	'last_updated_at' => 1653338064,
	'last_updated_by' => 1,
];