<?php 

return [
	'name' => 'Kalipso Next',
	'description' => '{"en":"It&amp;#039;s a site description.dfdsf","tr":"Bu bir site a&amp;ccedil;\u0131klamas\u0131."}',
	'contact_email' => 'halillusion@gmail.com',
	'separator' => '-',
	'language' => 'tr',
	'default_user_role' => 1,
	'ssl' => false,
	'log' => true,
	'maintenance_mode' => false,
	'maintenance_mode_desc' => '{"en":"We are under maintenance.","tr":"Bak\u0131m modunday\u0131z."}',
	'mail_send_type' => 'server',
	'smtp_address' => 'smtp.yandex.com.tr',
	'smtp_port' => 587,
	'smtp_email_address' => 'hi@example.com',
	'smtp_email_pass' => 'password',
	'smtp_secure' => 'tls',
	'mail_queue' => true,
	'view_cache' => false,
	'db_cache' => true,
	'route_cache' => false,
	'last_updated_at' => 1653387167,
	'last_updated_by' => 1,
];