<?php

/**
 * 	KalipsoNext - Localization File
 * 	English(en)
 **/

return [
    // APP
    'middleware_not_found'              => 'Middleware not found!',
    'controller_not_found'              => 'Controller not found!',
    'you_have_not_an_session'           => 'You have not an session!',
    'csrf_token_incorrect'              => 'The form token is incorrect!',
    'csrf_token_mismatch'               => 'The form token is mismatch!',

    // HELPER
    'byte'                              => 'byte',
    'plural_suffix'                     => 's',
    'undetected'                        => 'Undetected',

    // NOTIFICATIONS 
    'noti_unsubscribe_footer'           => 'If you want to unsubscribe from the e-mail newsletter, please <a href="[LINK]">click</a>.',
    'noti_email_register_title'         => 'Your Account Has Been Created!',
    'noti_email_register_body'          => 'Hi [USER], <br> your account has been created, welcome aboard. Please verify your email address with the link below. <br>[VERIFY_LINK]',
    'noti_sys_register_title'           => 'Welcome!',
    'noti_sys_register_body'            => 'Your account has been created.',
    'noti_email_recovery_request_title' => 'Account Recovery',
    'noti_email_recovery_request_body'  => 'Hi [USER],<br> We have received a request to recover your account. If you did not make this request, ignore it. We\'ve also left the link below to use to recover your account. <br>[RECOVERY_LINK]',
    'noti_email_recovery_account_title' => 'Your Account Has Been Recovered!',
    'noti_email_recovery_account_body'  => 'Hi [USER], <br>Your account has been successfully recovered, you can login with your new password. If you haven\'t done this, please get in touch.',
    'noti_email_change_title'           => 'Your Email Address Has Been Updated!',
    'noti_email_change_body'            => 'Hi [USER],<br> Your profile has just been updated. Please verify your email address with the link below. <br>[VERIFY_LINK]',

    // VIEWS
    'login'                             => 'Login',
    'register'                          => 'Register',
    'recovery_account'                  => 'Recovery Account',
    'account'                           => 'Account',
    'home'                              => 'Home',
    'email_or_username'                 => 'Email Address or Username',
    'email'                             => 'Email Address',
    'username'                          => 'Username',
    'password'                          => 'Password',
    'new_password'                      => 'New Password',
    'sign_in'                           => 'Sign In',
    'sign_up'                           => 'Sign Up',
    'welcome'                           => 'Welcome!',
    'back_to_home'                      => 'Back to Home',
    'prepare_database'                  => 'Prepare DB',
    'seed_database'                     => 'Seed DB',
    'php_info'                          => 'PHP Info',
    'alert'                             => 'Alert!',
    'form_cannot_empty'                 => 'Form cannot empty!',
    'account_not_found'                 => 'No such account was found.',
    'warning'                           => 'Warning!',
    'success'                           => 'Successful!',
    'logging_in'                        => 'Starting your session...',
    'logging_out'                       => 'Ending your session...',
    'your_account_has_been_blocked'     => 'Your account has been blocked, contact us.',
    'your_account_is_not_verified'      => 'Your account is not verified, check your email address.',
    'error'                             => 'Error!',
    'your_login_info_incorrect'         => 'Your login information is incorrect.',
    'start_session_problem'             => 'There was a problem signing in!',
    'profile_updated'                   => 'Your profile has been updated.',
    'profile_update_problem'            => 'There was a problem updating the profile!',
    'session'                           => 'Session',
    'a_problem_occurred'                => 'A problem occurred!',
    'you_have_a_session'                => 'You already have a session!',
    'you_have_not_a_session'            => 'You do not have a login yet!',
    'go_to_home'                        => 'Go to Home',
    'page_not_found'                    => 'Page not found!',
    'logout'                            => 'Logout',
    'username_is_already_used'          => 'Username is already in use.',
    'email_is_already_used'             => 'Email address is already in use.',
    'name'                              => 'Name',
    'surname'                           => 'Surname',
    'registration_problem'              => 'There was a problem saving information!',
    'registration_successful'           => 'Registration successful!',
    'verify_email'                      => 'Verify Email Address',
    'clear_storage'                     => 'Clear Storage Folder',
    'your_account_verified'             => 'Your account has been successfully verified.',
    'your_account_not_verified'         => 'Your account could not be verified.',
    'recovery_request_successful'       => 'You can recover your account with the link we sent to your email address.',
    'recovery_request_problem'          => 'There was a problem sending the account recovery link.',
    'recovery_account_successful'       => 'Your account has been successfully recovered.',
    'recovery_account_problem'          => 'There was a problem recovering your account.',
    'profile'                           => 'Profile',
    'sessions'                          => 'Sessions',
    'welcome_account'                   => 'Welcome! You can access the account pages where you can act from the side menu.',
    'first_name'                        => 'Name',
    'last_name'                         => 'Surname',
    'user_name'                         => 'Username',
    'birth_date'                        => 'Birth Date',
    'save'                              => 'Save',
    'no_record_found'                   => 'No record found!',
    'device'                            => 'Device',
    'ip'                                => 'IP',
    'last_action'                       => 'Last Action',
];