<?php

/**
 * 	KalipsoNext - Localization File
 * 	English(en)
 **/

return [
    'err' => 'Error',
    'error' => [
        'page_not_found' => 'Page not found!',
        'method_not_allowed' => 'Method not allowed!',
        'controller_not_defined' => 'Controller is not defined!',
        'unauthorized' => 'You are not authorized.',
        'view_definition_not_found' => 'Controller did not send view parameter!',
        'csrf_token_mismatch' => 'CSRF key mismatch.',
        'csrf_token_incorrect' => 'CSRF key invalid.',
        'username_is_already_used' => 'Username is already used.',
    ],
    'base' => [
        'sandbox' => 'Sandbox',
        'sandbox_message' => 'You can access all the tools that will help you in the development process from this screen.',
        'clear_storage' => 'Clear Storage',
        'clear_storage_message' => 'Allows you to delete files inside the storage folder.',
        'session' => 'Session',
        'session_message' => 'Shows the data within the session.',
        'php_info' => 'PHP Info',
        'php_info_message' => 'Shows server PHP information.',
        'db_init' => 'Prepare DB',
        'db_init_message' => 'Prepares database tables according to the schema.',
        'db_init_success' => 'Database has been prepared successfully.',
        'db_init_problem' => 'There was a problem while preparing the database. -> [ERROR]',
        'db_seed' => 'Seed DB',
        'db_seed_message' => 'Inserts data into tables within the schema.',
        'column' => 'Column',
        'table' => 'Table',
        'data' => 'Data',
        'type' => 'Type',
        'auto_inc' => 'Auto Increment',
        'attribute' => 'Attribute',
        'default' => 'Default',
        'index' => 'Index',
        'yes' => 'yes',
        'no' => 'no',
        'charset' => 'Charset',
        'collate' => 'Collate',
        'engine' => 'Engine',
        'db_name' => 'Database Name',
        'db_charset' => 'Database Charset',
        'db_collate' => 'Database Collate',
        'db_engine' => 'Database Engine',
        'db_init_alert' => 'If there is no database named [DB_NAME], add it with the [COLLATION] collation.',
        'db_init_start' => 'Good, Prepare!',
        'db_seed_success' => 'Database has been seeded successfully.',
        'db_seed_problem' => 'There was a problem while seeding the database. -> [ERROR]',
        'db_seed_start' => 'Good, Seed!',
        'clear_storage_success' => 'Storage folder is cleared.',
        'folder' => 'Folder',
        'delete' => 'Delete',
        'folder_not_found' => 'Folder not found!',
        'change_language' => 'Change Language',
        'seeding' => 'Seeding...',
        'go_to_home' => 'Go to Home',
        'home' => 'Home',
        'welcome' => 'Welcome!',
        'welcome_message' => 'It is the start page of KalipsoNext.', 
        'login' => 'Login',
        'login_message' => 'It is the sample login page.',
        'register' => 'Register',
        'register_message' => 'It is the sample register page.',
        'logout' => 'Logout',
        'account' => 'Account',
        'account_message' => 'It is the sample login page.',
        'email_or_username' => 'Email or Username',
        'password' => 'Password',
        'recovery_account' => 'Recovery Account',
        'email' => 'Email Address',
        'username' => 'Username', 
        'name' => 'Name',
        'surname' => 'Surname',
        'form_cannot_empty' => 'The form cannot be empty!',
        'email_is_already_used' => 'Email address is already in use.',
        'username_is_already_used' => 'Username is already in use.',
        'registration_problem' => 'There was a problem during registration.',
        'registration_successful' => 'Registration successful!',
    ],
    'app' => [
        
    ] 
];