<?php

/**
 * 	KalipsoNext - Localization File
 * 	Turkish(tr)
 **/

return [
    'err' => 'Hata',
    'error' => [
        'page_not_found' => 'Sayfa bulunamadı!',
        'method_not_allowed' => 'Methoda izin verilmez!',
        'controller_not_defined' => 'Kontrolcü tanımlanmamış!',
        'unauthorized' => 'Yetkiniz yok.',
        'view_definition_not_found' => 'Kontrolcü, görüntüleme parametresi göndermedi!',
    ],
    'base' => [
        'welcome' => 'Hoş geldiniz!',
        'welcome_message' => 'KalipsoNext\'in başlangıç sayfasıdır.',
        'login' => 'Giriş Yap',
        'login_message' => 'Örnek giriş sayfasıdır.',
        'account' => 'Hesap',
        'account_message' => 'Örnek hesap sayfasıdır.',
        'sandbox' => 'Geliştirici Araçları',
        'sandbox_message' => 'Geliştirme sürecinde size yardımcı olacak tüm araçlara bu ekrandan ulaşabilirsiniz.',
        'clear_storage' => 'Klasörleri Temizle',
        'clear_storage_message' => 'Depolama klasörü içindeki dosyaları silmenizi sağlar.',
        'session' => 'Oturum',
        'session_message' => 'Oturum içindeki verileri gösterir.',
        'php_info' => 'PHP Bilgileri',
        'php_info_message' => 'Sunucu PHP bilgilerini gösterir.',
        'db_init' => 'Veri Tabanını Hazırla',
        'db_init_message' => 'Şemaya göre veri tabanı tablolarını hazırlar.',
        'db_init_success' => 'Veri tabanı başarıyla hazırlandı.',
        'db_init_problem' => 'Veritabanı hazırlanırken bir sorun oluştu. -> [ERROR]',
        'db_seed' => 'Veri Tabanını Doldur',
        'db_seed_message' => 'Şema içeriğinde verileri tablolara ekler.',
        'column' => 'Sütun',
        'data' => 'Veri',
        'table' => 'Tablo',
        'type' => 'Tip',
        'auto_inc' => 'Otomatik Artan',
        'attribute' => 'Özellik',
        'default' => 'Varsayılan',
        'index' => 'İndis',
        'yes' => 'evet',
        'no' => 'yes',
        'charset' => 'Karakter Seti',
        'collate' => 'Karşılaştırma Seti',
        'engine' => 'Motor',
        'db_name' => 'Veri Tabanı İsmi',
        'db_charset' => 'Veri Tabanı Karakter Seti',
        'db_collate' => 'Veri Tabanı Karşılaştırma Seti',
        'db_engine' => 'Veri Tabanı Motoru',
        'db_init_alert' => '[DB_NAME] adında bir veritabanı yoksa, [COLLATION] karşılaştırma seti ayarıyla ekleyin.',
        'db_init_start' => 'Harika, Hazırla!',
        'db_seed_success' => 'Veri tabanı başarıyla içe aktarıldı.',
        'db_seed_problem' => 'Veritabanı içe aktarılırken bir sorun oluştu. -> [ERROR]',
        'db_seed_start' => 'Harika, İçe Aktar!',
        'clear_storage_success' => 'Depolama klasörü temizlendi.',
        'folder' => 'Klasör',
        'delete' => 'Sil',
        'folder_not_found' => 'Klasör bulunamadı!',
        'change_language' => 'Dili Değiştir',
    ]
];